### ISSUE TITLE
Extract :engine:api module

### ISSUE THREAD

**Issue by Subtle-fox** [JaverSingleton/bdui#39]
Вынести публичные классы и интерфейсы в апи-модуль. Подключать к остальным именно его

**Comment by JaverSingleton** [comment]
Это нам как-то поможет в рамках подключения к другим платформам?

**Comment by Subtle-fox** [comment]
Заводил эту задачу до созвона с тобой и Игорем (когда рассказывал про js, и когда мы экспериментировали с экспортом). Тогда была идея вынести апи и промаркировать все апи-интерфейсы аннотацией JsExport.
Но после обсуждения в свете того, что ты планируешь упрощать интерфейсы, которые будут торчать наружу, задача теряет актуальность. Можно закрыть
